### PR TITLE
Add .prettierignore and reformat repository

### PR DESCRIPTION
**Pull request by henrik-dmg**
Hi there, this is a simple one.

## Changes

- added `.prettierignore` files
- ran `prettier --write "**/*.{js,ts,jsx,tsx,md}" --config prettier.config.js --ignore-path .prettierignore` and committed changes

Could be cool if we had a pre-commit hook for this for example :) or a Github Action that lints

### CODE REVIEW

**Comment by nrjdalal** [comment]
I would welcome this commit, just add husky for pre-commit use-case :) and add the script to package.json

**Comment by henrik-dmg** [comment]
Awesome, I added the changes to this PR 🙂  I followed the steps here:

https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged

**Comment by nrjdalal** [comment]
would check changes shortly during this week, thank you for contributing :D

**Comment by henrik-dmg** [comment]
Any updates? 🙂

**Comment by nrjdalal** [comment]
need to see lint-staged as it is new to me, didn't get the time yet, sorry for that, will surely merge if lint staged works for me to in next 2-3 days

**Pull request merged**
